In [35]:
# pip install scikit-learn
import pandas as pd
from sklearn.model_selection import train_test_split

In [24]:
import pandas as pd
data = pd.read_csv("data/bank_data.csv")
data.head(2)

data.shape

(60, 3)

In [25]:
data.head(2) # select top 2 * from data

   cibil_score   income    status
0          610  ₹15,000  Rejected
1          760  ₹55,000  Approved

In [26]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   cibil_score  60 non-null     int64
 1   income       60 non-null     str
 2   status       60 non-null     str
dtypes: int64(1), str(2)
memory usage: 1.5 KB

In [27]:
data.status.value_counts()

status
Rejected    30
Approved    30
Name: count, dtype: int64

In [28]:
def category(x):
    if x =='Rejected':
        return 0
    else:
        return 1

def formate_income(x):
    return int(x.split('₹')[1].replace(',',''))

In [29]:
data['status'] = data['status'].apply(category)
data['income'] = data['income'].apply(formate_income)

In [30]:
data.head(5)

   cibil_score  income  status
0          610   15000       0
1          760   55000       1
2          670   35000       1
3          775   48000       1
4          735   32000       1

In [31]:
# int('₹35,000'.split('₹')[1].replace(',',''))
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   cibil_score  60 non-null     int64
 1   income       60 non-null     int64
 2   status       60 non-null     int64
dtypes: int64(3)
memory usage: 1.5 KB

In [32]:
X = data[['cibil_score','income']]
y = data['status']

In [45]:
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size=0.1)

In [ ]:
x_train.shape,y_train.shape
x_test.shape,y_test.shape

((54, 2), (54,))

In [74]:
from sklearn.neighbors import KNeighborsClassifier

# step 1 : setting up all the param --> if you dont ---> default param
knn = KNeighborsClassifier(n_neighbors=8)


# ste2 : training the model
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=8)

In [75]:
x_test.head()

    cibil_score  income
11          620   12000
20          530   17000
40          760   40000
29          695   29000
8           490   30000

In [76]:
# test the model
test = [850,25000]
knn.predict(x_test)

array([0, 0, 1, 1, 1, 0])

In [77]:
y_test

11    0
20    0
40    1
29    0
8     0
31    0
Name: status, dtype: int64

In [78]:
test_df = x_test.copy()

In [79]:
test_df['actual'] = y_test
test_df['predicted'] = knn.predict(x_test)

test_df

    cibil_score  income  actual  predicted
11          620   12000       0          0
20          530   17000       0          0
40          760   40000       1          1
29          695   29000       0          1
8           490   30000       0          1
31          500   10000       0          0

In [80]:
import pickle

# Save the model
with open('models/my__gpt_v1.pkl', 'wb') as f:
    pickle.dump(knn, f)

In [53]:
knn

KNeighborsClassifier(n_neighbors=3)

In [33]:
X

    cibil_score  income
0           610   15000
1           760   55000
2           670   35000
3           775   48000
4           735   32000
5           700   30000
6           640   38000
7           645   42000
8           490   30000
9           780   68000
10          830   90000
11          620   12000
12          510   20000
13          480   50000
14          480   25000
15          515   48000
16          760   38000
17          710   31000
18          650   28000
19          820   75000
20          530   17000
21          755   35000
22          665   24000
23          730   45000
24          560   28000
25          790   72000
26          750   45000
27          545   38000
28          480   12000
29          695   29000
30          760   50000
31          500   10000
32          590    9000
33          520   15000
34          500   42000
35          800   65000
36          600   10000
37          530   40000
38          540   18000
39          660   32000
40          760   40000
41          510   45000
42          685   31000
43          800   60000
44          450    8000
45          580    8000
46          740   33000
47          520   22000
48          680   27000
49          520   32000
50          810   80000
51          655   26000
52          790   55000
53          850  100000
54          720   30000
55          745   36000
56          530   55000
57          780   52000
58          770   42000
59          540   35000

In [34]:
y

0     0
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     0
9     1
10    1
11    0
12    0
13    0
14    0
15    0
16    1
17    1
18    0
19    1
20    0
21    1
22    0
23    1
24    0
25    1
26    1
27    0
28    0
29    0
30    1
31    0
32    0
33    0
34    0
35    1
36    0
37    0
38    0
39    1
40    1
41    0
42    1
43    1
44    0
45    0
46    1
47    0
48    0
49    0
50    1
51    0
52    1
53    1
54    1
55    1
56    0
57    1
58    1
59    0
Name: status, dtype: int64