In [38]:
import pandas as pd
data = pd.read_csv("data.csv")
data.head(5)

# shortcut ==? shift + enter/ctrl + enter

,batch_name,session_date,session_name,user_id,rating,subjective_feedback,feedback_date
0,IIT Mandi iHub | Deployment and Project Integr...,"19 Sep, 2026",Cont : Building APIs with FastAPI,"286,804",5,NaN,"19 Sep, 2026"
1,Deployment and Project Integration 16 Aug 2026,"19 Sep, 2026",Cont : Building APIs with FastAPI,"12,076,162",5,Excellent. Rahul is working hard to get things...,"19 Sep, 2026"
2,Deployment and Project Integration 16 Aug 2026,"19 Sep, 2026",Cont : Building APIs with FastAPI,"11,862,397",5,NaN,"19 Sep, 2026"
3,Deployment and Project Integration 16 Aug 2026,"19 Sep, 2026",Cont : Building APIs with FastAPI,"1,085,640",5,NaN,"19 Sep, 2026"
4,Deployment and Project Integration 16 Aug 2026,"19 Sep, 2026",Cont : Building APIs with FastAPI,"5,938,235",5,NaN,"19 Sep, 2026"

In [24]:
data['batch_name'].nunique()

15

In [76]:
def custom_cal(x):
    return x * 2

In [78]:
data.groupby(['batch_name','session_name']).agg({'rating':['mean','max','min'],
                                                 })

                                                                                                         rating  \
                                                                                                           mean
batch_name                                         session_name
AI Agents and Multi-Agent Systems 02 Jul 2026      AI Communication Protocols & Building an MCP Se...  5.000000
                                                   Agent Evaluation & Debugging                        5.000000
                                                   Agents Architecture & Design Patterns               5.000000
                                                   Building Blocks of AI Agents                        4.800000
                                                   Building Multi-Agent System                         5.000000
...                                                                                                         ...
Prompt Engineering and API Integration 03 Apr 2026 Github and VScode Installation                      5.000000
                                                   In-Class Project Session 1: ScamGuard AI            4.900000
                                                   In-Class Project Session 2: ScamGuard AI            5.000000
                                                   Overview of GenAI Platforms                         4.521739
                                                   Understanding and Evaluating Generative AI Outputs  5.000000

                                                                                                           \
                                                                                                      max
batch_name                                         session_name
AI Agents and Multi-Agent Systems 02 Jul 2026      AI Communication Protocols & Building an MCP Se...   5
                                                   Agent Evaluation & Debugging                         5
                                                   Agents Architecture & Design Patterns                5
                                                   Building Blocks of AI Agents                         5
                                                   Building Multi-Agent System                          5
...                                                                                                    ..
Prompt Engineering and API Integration 03 Apr 2026 Github and VScode Installation                       5
                                                   In-Class Project Session 1: ScamGuard AI             5
                                                   In-Class Project Session 2: ScamGuard AI             5
                                                   Overview of GenAI Platforms                          5
                                                   Understanding and Evaluating Generative AI Outputs   5


                                                                                                      min
batch_name                                         session_name
AI Agents and Multi-Agent Systems 02 Jul 2026      AI Communication Protocols & Building an MCP Se...   5
                                                   Agent Evaluation & Debugging                         5
                                                   Agents Architecture & Design Patterns                5
                                                   Building Blocks of AI Agents                         4
                                                   Building Multi-Agent System                          5
...                                                                                                    ..
Prompt Engineering and API Integration 03 Apr 2026 Github and VScode Installation                       5
                                                   In-Class Project Session 1: ScamGuard AI             4
                                                   In-Class Project Session 2: ScamGuard AI             5
                                                   Overview of GenAI Platforms                          3
                                                   Understanding and Evaluating Generative AI Outputs   5

[102 rows x 3 columns]

In [28]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 530 entries, 0 to 529
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   batch_name           530 non-null    str
 1   session_date         530 non-null    str
 2   session_name         530 non-null    str
 3   user_id              530 non-null    str
 4   rating               530 non-null    int64
 5   subjective_feedback  239 non-null    str
 6   feedback_date        530 non-null    str
dtypes: int64(1), str(6)
memory usage: 29.1 KB

In [33]:

data['session_date'] = pd.to_datetime(data['session_date']).dt.strftime('%d-%m-%Y')

/var/folders/fq/kr6gv5l17pd4j572n0_n3f2c0000gn/T/ipykernel_2216/3719301583.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  data['session_date'] = pd.to_datetime(data['session_date']).dt.strftime('%d-%m-%Y')

In [41]:
data['session_date'] = pd.to_datetime(data['session_date'])
data['feedback_date'] = pd.to_datetime(data['feedback_date'])

In [47]:
data['month'] = data['session_date'].dt.month
data['year'] = data['session_date'].dt.year
data['day'] = data['session_date'].dt.day
data['week'] = data['session_date'].dt.isocalendar().week

In [52]:
data.groupby(['batch_name','session_name']).agg({'rating':['mean','max','min'],
                                                 'day':['min']
                                                 }).to_csv('output.csv')

In [ ]:
# join --> left right inner outer ( sql)

In [58]:
finance = pd.read_csv("finance.csv")
sales = pd.read_csv("sales.csv")
inventory = pd.read_csv("inventory.csv")

In [71]:
pd.merge(sales, inventory[['sku','name']], on='sku', how='left').to_csv('output_1.csv')

In [68]:
inventory.head(2)

,sku,name,category,region,qty,reorder_threshold,unit_cost,vendor_id
0,SKU001,Mixer Grinder,Kitchen Appliances,North,41,16,3500,V001
1,SKU002,Pressure Cooker,Kitchen Appliances,North,55,30,2500,V018

In [66]:
# inventory.info()

In [63]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 9157 entries, 0 to 9156
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               9157 non-null   str
 1   sku                9157 non-null   str
 2   qty                9157 non-null   int64
 3   revenue            9157 non-null   float64
 4   region             9157 non-null   str
 5   temperature        9157 non-null   str
 6   rainfall           9157 non-null   float64
 7   humidity           9157 non-null   float64
 8   weather_condition  9157 non-null   str
dtypes: float64(3), int64(1), str(5)
memory usage: 644.0 KB

In [67]:
# sales.join(inventory, on='sku', how='left')

In [54]:
sales.head(2)

,date,sku,qty,revenue,region,temperature,rainfall,humidity,weather_condition
0,2022-10-03,SKU060,1,3953.37,North,16.7,40.9,67.0,Rainy
1,2020-06-22,SKU058,9,18397.09,South,24.4,57.4,82.0,Rainy

In [57]:
sales.sku.value_counts()

sku
SKU030    123
SKU029    119
SKU091    118
SKU043    115
SKU057    111
         ...
SKU038     73
SKU062     72
SKU073     72
SKU027     69
SKU063     68
Name: count, Length: 100, dtype: int64

In [55]:
finance.head(2)

   id     sku        date   amount      type region
0   1  SKU069  2019-11-01  12090.0      sale   West
1   2  SKU059  2019-11-02  32500.0  purchase  North

In [75]:
data_val = {
    'id':[1,2,3,4,5],
    'sales': [100, 200, 300, 400, 500],
    'inventory': [50, 60, 70, 80, 90]
}

pd.DataFrame(data_val,index=[4, 5, 6, 7, 8])

   id  sales  inventory
4   1    100         50
5   2    200         60
6   3    300         70
7   4    400         80
8   5    500         90

In [ ]:
# https://pandas.pydata.org/docs/user_guide/merging.html

In [45]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 530 entries, 0 to 529
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   batch_name           530 non-null    str
 1   session_date         530 non-null    datetime64[us]
 2   session_name         530 non-null    str
 3   user_id              530 non-null    str
 4   rating               530 non-null    int64
 5   subjective_feedback  239 non-null    str
 6   feedback_date        530 non-null    datetime64[us]
 7   month                530 non-null    int32
 8   year                 530 non-null    int32
 9   day                  530 non-null    int32
dtypes: datetime64[us](2), int32(3), int64(1), str(4)
memory usage: 35.3 KB

In [48]:
data.head()

,batch_name,session_date,session_name,user_id,rating,subjective_feedback,feedback_date,month,year,day,week
0,IIT Mandi iHub | Deployment and Project Integr...,2026-09-19,Cont : Building APIs with FastAPI,"286,804",5,NaN,2026-09-19,9,2026,19,38
1,Deployment and Project Integration 16 Aug 2026,2026-09-19,Cont : Building APIs with FastAPI,"12,076,162",5,Excellent. Rahul is working hard to get things...,2026-09-19,9,2026,19,38
2,Deployment and Project Integration 16 Aug 2026,2026-09-19,Cont : Building APIs with FastAPI,"11,862,397",5,NaN,2026-09-19,9,2026,19,38
3,Deployment and Project Integration 16 Aug 2026,2026-09-19,Cont : Building APIs with FastAPI,"1,085,640",5,NaN,2026-09-19,9,2026,19,38
4,Deployment and Project Integration 16 Aug 2026,2026-09-19,Cont : Building APIs with FastAPI,"5,938,235",5,NaN,2026-09-19,9,2026,19,38

In [ ]:
-- SELECT AVG(rating) FROM table_name;

In [ ]:
# data['rating'].mean() # SELECT AVG(rating) FROM table_name;

np.float64(4.788679245283019)

In [ ]:
# python ---> pandas/spark --> data ,analysis
# sql --> sql query

In [ ]:
# data.tail(5)
# connection = sqlite3.connect("database.db")
# connection = sqlite3.connect("database.db")
# pd.read_sql("SELECT * FROM table_name", con=connection)

In [ ]:
# display(data)

,batch_name,session_date,session_name,user_id,rating,subjective_feedback,feedback_date
0,IIT Mandi iHub | Deployment and Project Integr...,"19 Sep, 2026",Cont : Building APIs with FastAPI,"286,804",5,NaN,"19 Sep, 2026"
1,Deployment and Project Integration 16 Aug 2026,"19 Sep, 2026",Cont : Building APIs with FastAPI,"12,076,162",5,Excellent. Rahul is working hard to get things...,"19 Sep, 2026"
2,Deployment and Project Integration 16 Aug 2026,"19 Sep, 2026",Cont : Building APIs with FastAPI,"11,862,397",5,NaN,"19 Sep, 2026"
3,Deployment and Project Integration 16 Aug 2026,"19 Sep, 2026",Cont : Building APIs with FastAPI,"1,085,640",5,NaN,"19 Sep, 2026"
4,Deployment and Project Integration 16 Aug 2026,"19 Sep, 2026",Cont : Building APIs with FastAPI,"5,938,235",5,NaN,"19 Sep, 2026"
...,...,...,...,...,...,...,...
525,Prompt Engineering and API Integration 03 Apr ...,"4 Apr, 2026",Foundations of Generative AI,"12,033,466",5,NaN,"4 Apr, 2026"
526,Prompt Engineering and API Integration 03 Apr ...,"4 Apr, 2026",Foundations of Generative AI,"12,041,542",5,NaN,"4 Apr, 2026"
527,IBM | Prompt Engineering and API Integration 0...,"4 Apr, 2026",Foundations of Generative AI,"11,539,113",5,NaN,"4 Apr, 2026"
528,Prompt Engineering and API Integration 03 Apr ...,"4 Apr, 2026",Foundations of Generative AI,"11,959,570",4,NaN,"4 Apr, 2026"
529,IBM | Prompt Engineering and API Integration 0...,"4 Apr, 2026",Foundations of Generative AI,"12,022,341",4,"It was nice, just a lot of interruptions in be...","4 Apr, 2026"

In [ ]:
# x = 3
# print(x)
# type(data)

3

pandas.DataFrame

## Conclusion
- There are 7 columns
- Data is about xyz